/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSetupPasswordRouteImport } from './routes/auth/setup-password'
import { Route as AuthPendingVerificationRouteImport } from './routes/auth/pending-verification'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin.requests.index'
import { Route as ProtectedUnlocksIndexRouteImport } from './routes/_protected/unlocks/index'
import { Route as ProtectedRequestsIndexRouteImport } from './routes/_protected/requests/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedCompaniesIndexRouteImport } from './routes/_protected/companies/index'
import { Route as AdminRequestsRequestIdRouteImport } from './routes/admin.requests.$requestId'
import { Route as ProtectedRequestsRequestIdRouteImport } from './routes/_protected/requests/$requestId'
import { Route as ProtectedCompaniesCompanyIdRouteImport } from './routes/_protected/companies/$companyId'
import { Route as ProtectedRequestsPaymentFailedRequestIdRouteImport } from './routes/_protected/requests/payment-failed.$requestId'
import { Route as ProtectedRequestsNewIndividualsRouteImport } from './routes/_protected/requests/new.individuals'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupPasswordRoute = AuthSetupPasswordRouteImport.update({
  id: '/auth/setup-password',
  path: '/auth/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingVerificationRoute = AuthPendingVerificationRouteImport.update({
  id: '/auth/pending-verification',
  path: '/auth/pending-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/admin/requests/',
  path: '/admin/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUnlocksIndexRoute = ProtectedUnlocksIndexRouteImport.update({
  id: '/unlocks/',
  path: '/unlocks/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRequestsIndexRoute = ProtectedRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCompaniesIndexRoute = ProtectedCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AdminRequestsRequestIdRoute = AdminRequestsRequestIdRouteImport.update({
  id: '/admin/requests/$requestId',
  path: '/admin/requests/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRequestsRequestIdRoute =
  ProtectedRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCompaniesCompanyIdRoute =
  ProtectedCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedRequestsPaymentFailedRequestIdRoute =
  ProtectedRequestsPaymentFailedRequestIdRouteImport.update({
    id: '/requests/payment-failed/$requestId',
    path: '/requests/payment-failed/$requestId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedRequestsNewIndividualsRoute =
  ProtectedRequestsNewIndividualsRouteImport.update({
    id: '/requests/new/individuals',
    path: '/requests/new/individuals',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/services': typeof AdminServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/requests/$requestId': typeof ProtectedRequestsRequestIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/companies/': typeof ProtectedCompaniesIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/requests/': typeof ProtectedRequestsIndexRoute
  '/unlocks/': typeof ProtectedUnlocksIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/requests/new/individuals': typeof ProtectedRequestsNewIndividualsRoute
  '/requests/payment-failed/$requestId': typeof ProtectedRequestsPaymentFailedRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/services': typeof AdminServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/requests/$requestId': typeof ProtectedRequestsRequestIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/companies': typeof ProtectedCompaniesIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/requests': typeof ProtectedRequestsIndexRoute
  '/unlocks': typeof ProtectedUnlocksIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/requests/new/individuals': typeof ProtectedRequestsNewIndividualsRoute
  '/requests/payment-failed/$requestId': typeof ProtectedRequestsPaymentFailedRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/admin/services': typeof AdminServicesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/pending-verification': typeof AuthPendingVerificationRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_protected/companies/$companyId': typeof ProtectedCompaniesCompanyIdRoute
  '/_protected/requests/$requestId': typeof ProtectedRequestsRequestIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/_protected/companies/': typeof ProtectedCompaniesIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/requests/': typeof ProtectedRequestsIndexRoute
  '/_protected/unlocks/': typeof ProtectedUnlocksIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/_protected/requests/new/individuals': typeof ProtectedRequestsNewIndividualsRoute
  '/_protected/requests/payment-failed/$requestId': typeof ProtectedRequestsPaymentFailedRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/services'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/setup-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/companies/$companyId'
    | '/requests/$requestId'
    | '/admin/requests/$requestId'
    | '/companies/'
    | '/dashboard/'
    | '/requests/'
    | '/unlocks/'
    | '/admin/requests/'
    | '/requests/new/individuals'
    | '/requests/payment-failed/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/services'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/setup-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/companies/$companyId'
    | '/requests/$requestId'
    | '/admin/requests/$requestId'
    | '/companies'
    | '/dashboard'
    | '/requests'
    | '/unlocks'
    | '/admin/requests'
    | '/requests/new/individuals'
    | '/requests/payment-failed/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/admin/services'
    | '/auth/login'
    | '/auth/pending-verification'
    | '/auth/setup-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/_protected/companies/$companyId'
    | '/_protected/requests/$requestId'
    | '/admin/requests/$requestId'
    | '/_protected/companies/'
    | '/_protected/dashboard/'
    | '/_protected/requests/'
    | '/_protected/unlocks/'
    | '/admin/requests/'
    | '/_protected/requests/new/individuals'
    | '/_protected/requests/payment-failed/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AdminServicesRoute: typeof AdminServicesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPendingVerificationRoute: typeof AuthPendingVerificationRoute
  AuthSetupPasswordRoute: typeof AuthSetupPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AdminRequestsRequestIdRoute: typeof AdminRequestsRequestIdRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup-password': {
      id: '/auth/setup-password'
      path: '/auth/setup-password'
      fullPath: '/auth/setup-password'
      preLoaderRoute: typeof AuthSetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pending-verification': {
      id: '/auth/pending-verification'
      path: '/auth/pending-verification'
      fullPath: '/auth/pending-verification'
      preLoaderRoute: typeof AuthPendingVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/unlocks/': {
      id: '/_protected/unlocks/'
      path: '/unlocks'
      fullPath: '/unlocks/'
      preLoaderRoute: typeof ProtectedUnlocksIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/requests/': {
      id: '/_protected/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof ProtectedRequestsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/companies/': {
      id: '/_protected/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof ProtectedCompaniesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/admin/requests/$requestId': {
      id: '/admin/requests/$requestId'
      path: '/admin/requests/$requestId'
      fullPath: '/admin/requests/$requestId'
      preLoaderRoute: typeof AdminRequestsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/requests/$requestId': {
      id: '/_protected/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof ProtectedRequestsRequestIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/companies/$companyId': {
      id: '/_protected/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof ProtectedCompaniesCompanyIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/requests/payment-failed/$requestId': {
      id: '/_protected/requests/payment-failed/$requestId'
      path: '/requests/payment-failed/$requestId'
      fullPath: '/requests/payment-failed/$requestId'
      preLoaderRoute: typeof ProtectedRequestsPaymentFailedRequestIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/requests/new/individuals': {
      id: '/_protected/requests/new/individuals'
      path: '/requests/new/individuals'
      fullPath: '/requests/new/individuals'
      preLoaderRoute: typeof ProtectedRequestsNewIndividualsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedCompaniesCompanyIdRoute: typeof ProtectedCompaniesCompanyIdRoute
  ProtectedRequestsRequestIdRoute: typeof ProtectedRequestsRequestIdRoute
  ProtectedCompaniesIndexRoute: typeof ProtectedCompaniesIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedRequestsIndexRoute: typeof ProtectedRequestsIndexRoute
  ProtectedUnlocksIndexRoute: typeof ProtectedUnlocksIndexRoute
  ProtectedRequestsNewIndividualsRoute: typeof ProtectedRequestsNewIndividualsRoute
  ProtectedRequestsPaymentFailedRequestIdRoute: typeof ProtectedRequestsPaymentFailedRequestIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCompaniesCompanyIdRoute: ProtectedCompaniesCompanyIdRoute,
  ProtectedRequestsRequestIdRoute: ProtectedRequestsRequestIdRoute,
  ProtectedCompaniesIndexRoute: ProtectedCompaniesIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedRequestsIndexRoute: ProtectedRequestsIndexRoute,
  ProtectedUnlocksIndexRoute: ProtectedUnlocksIndexRoute,
  ProtectedRequestsNewIndividualsRoute: ProtectedRequestsNewIndividualsRoute,
  ProtectedRequestsPaymentFailedRequestIdRoute:
    ProtectedRequestsPaymentFailedRequestIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AdminServicesRoute: AdminServicesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPendingVerificationRoute: AuthPendingVerificationRoute,
  AuthSetupPasswordRoute: AuthSetupPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AdminRequestsRequestIdRoute: AdminRequestsRequestIdRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
